### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by konstantinosKokos** [konstantinosKokos/dyck-paper#1]
* [x] consistent captioning
* [x] consistent citation styling
* [x] commas in citations
* [x] bibst
* [x] something forgotten (?)
  * [x] straddling (add example from presentation)
* [x] add actual values to placeholder tables, maybe restyle
